In [10]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [11]:
a=np.array([1,2,3])

In [12]:
b=np.array([4,5,6])

In [13]:
print(np.dot(a,b))

32


In [14]:
x= np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [15]:
x

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

In [16]:
x.shape

(4, 4)

In [17]:
a=np.matrix([[1,4,3],[2,5,6],[3,7,9]])

In [18]:
a

matrix([[1, 4, 3],
        [2, 5, 6],
        [3, 7, 9]])

In [19]:
b=np.matrix([[1,4,3],[2,5,6],[3,7,9]])

In [20]:
b

matrix([[1, 4, 3],
        [2, 5, 6],
        [3, 7, 9]])

In [21]:
b.shape

(3, 3)

In [22]:
print(a*b)

[[ 18  45  54]
 [ 30  75  90]
 [ 44 110 132]]


In [23]:
from numpy import linalg as LA

In [24]:
x= np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [26]:
x.shape

(3, 3)

In [27]:
LA.matrix_rank(x)

2